apiVersion: skaffold/v2beta10
kind: Config
build:
  tagPolicy:
    # gitCommit: {}
    envTemplate:
      template: "{{.IMAGE_NAME}}:{{.CI_COMMIT_SHORT_SHA}}"
  artifacts:
  - image: [FULLREPO]
    kaniko:
      useNewRun: true
      dockerfile: ./Dockerfile
      cache: {}
  cluster:
    pullSecretName: kaniko-secret
    namespace: gitlab-runner
deploy:
  helm:
    releases:
    - name: [IMAGE_NAME_CI]
      chartPath: helm-template
      namespace: [NAMESPACE]
      artifactOverrides:
        image.repository: [FULLREPO]
      valuesFiles:
        - helm/[HELM_VALUE].yaml
